# Generated by Django 3.0.2 on 2021-02-21 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionPapers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_of_subject', models.CharField(max_length=200)),
                ('name_of_subject', models.CharField(max_length=200)),
                ('code_of_subject', models.CharField(max_length=200)),
                ('type_of_paper', models.CharField(max_length=200)),
                ('question_paper_image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
