# Generated by Django 3.0.2 on 2021-02-22 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_questionpapers_question_paper_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionpapers',
            name='question_paper_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
