# Generated by Django 3.0.2 on 2021-02-22 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_questionpapers_question_paper_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionpapers',
            name='semester',
            field=models.CharField(default=1, max_length=10),
        ),
    ]
